name: Generate UUID

inputs:
  name:
    description: placeholder
    required: false
  namespace:
    description: placeholder
    required: false

outputs:
  uuid:
    description: placeholder
    value: ${{ steps.uuid.outputs.uuid }}

runs:
  using: composite
  steps:
    - name: Set Up uv
      uses: astral-sh/setup-uv@v4

    - name: Generate UUID
      id: uuid
      shell: bash
      run: uv run ${{ github.action_path }}/uuidgen.py