name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate UUID
        id: uuid
        uses: celsiusnarhwal/uuid-action@main

      - name: Print UUID Info
        run: echo ${{ steps.uuid.outputs.json }}